#config_version=6

# Battle Of The Bands v1.3  MPF 0.80 / GMC 0.1.2 / G'Doh! 4.3

# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.

mode_settings:
    selectable_items:
        - title
        - game_over
        - credits
        - last_scores_1p{machine.player1_score and not machine.player2_score}
        - last_scores_2p{machine.player2_score and not machine.player3_score}
        - last_scores_3p{machine.player3_score and not machine.player4_score}
        - last_scores_4p{machine.player4_score}
        - featured_bands
        - high_scores
        - mpf_logo
    next_item_events: s_right_flipper_lower_active, timer_attract_carousel_timer_complete
    previous_item_events: s_left_flipper_lower_active

slide_player:
    mode_attract_started:
        attract_primary_slide:
            target: primary
        attract_mini_slide:
            target: mini-display

sound_player:
  mode_attract_started:
#    themysteriousreturnintro:
#    hauntedcastleserenade_intro:
#    arp_livedourlivesbeforemusic:
#    lost23prequel_intro:
    arp_longliverockogg22:
#    preludeofdoom_intro:
#    preludetothemoon_intro:
#    theguillotinesuite_intro:
      bus: music

timers:
    attract_carousel_timer:
        end_value: 1
        tick_interval: 5s
        start_running: true
        control_events:
#            - event: item_highlited
#              action: restart
            - event: flipper_cradle
              action: stop
            - event: flipper_cradle_release
              action: restart
            - event: timer_attract_carousel_timer_complete
              action: restart
            - event: s_left_flipper_lower_active
              action: restart
            - event: s_right_flipper_lower_active
              action: restart


#event_player:
#  timer_attract_carousel_timer_complete: random_lights
#    light_player:
#   led_code:
#      l_ballinplay1: "DFFF00"
#   led_off:
#      l_ballinplay1: off
#      l_ballinplay2: off
#   led_name:
#      l_ballinplay2: LightSalmon
#  group_light:
#      group1: green
#   led_fade:
#      l_ballinplay1:
#       color: slateblue
#       fade: 2000ms
#


# from Tag Team      mystery.yaml
#event_player:
#   sw_pops{(current_player.popHitsTotal+1)%65==0}: enable_mystery
#   s_topRollunder_active{current_player.mystery_enabled==1}: select_mystery


#random_event_player:
#   select_mystery:
#      events:
#         mysteryAward_ExtraBall_event: 10 #numbers show probability of event
#         mysteryAward_MaxBonus_event: 15
#         mysteryAward_MaxSkill_event: 10
#         mysteryAward_MaxPop_event: 20
#         mysteryAward_UnlimitedChances_event: 10
#         mysteryAward_AdvJackpot_event: 15
#         mysteryAward_ScoringX_event: 20

#random_event_player:
#  random_lights:
#    events:
#      alllightson: 50
#      alllightsoff: 50

#show_player:
#  alllightson:
#    light_player:
#     group_light:
#        group1: green
#        gi: white

#  alllightsoff:
#    light_player:
#      group_light:
#       group1: red
#        gi: blue
