#config_version=6

# Battle Of The Bands v1.3  MPF 0.80 / GMC 0.1.2 / G'Doh! 4.3

# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.

mode_settings:
    selectable_items:
        - title
        - game_over
        - credits
        - last_scores_1p{machine.player1_score and not machine.player2_score}
        - last_scores_2p{machine.player2_score and not machine.player3_score}
        - last_scores_3p{machine.player3_score and not machine.player4_score}
        - last_scores_4p{machine.player4_score}
        - featured_bands
        - high_scores
        - mpf_logo
    next_item_events: s_right_flipper_lower_active, timer_attract_carousel_timer_complete
    previous_item_events: s_left_flipper_lower_active

slide_player:
    mode_attract_started:
        attract_primary_slide:
            target: primary
        attract_mini_slide:
            target: mini-display

sound_player:
  mode_attract_started:
#    themysteriousreturnintro:
#    hauntedcastleserenade_intro:
#    arp_livedourlivesbeforemusic:
#    lost23prequel_intro:
    arp_longliverockogg22:
#    preludeofdoom_intro:
#    preludetothemoon_intro:
#    theguillotinesuite_intro:
      bus: music

timers:
    attract_carousel_timer:
        end_value: 1
        tick_interval: 5s
        start_running: true
        control_events:
#            - event: item_highlited
#              action: restart
            - event: flipper_cradle
              action: stop
            - event: flipper_cradle_release
              action: restart
            - event: timer_attract_carousel_timer_complete
              action: restart
            - event: s_left_flipper_lower_active
              action: restart
            - event: s_right_flipper_lower_active
              action: restart

# FROM TAG TEAM FOR EXAMPLE
#show_player:
#    mode_attract_started:
#        attract_display_loop:
#            speed: 1
#        attract_segment_loop:
#            speed: 1
#        attract_light_show:
#            speed: 15
#        attract_light_show_drop:
#            speed: 0.75
#        color_on:
#            show_tokens:
#                color: tt_yellow
#                led: l_leftCoin, l_rightCoin
#        sequenceColor:
#            speed: 6
#            priority: 3
#            show_tokens:
#                color: tt_white
#                led: l_popLeft, l_topRollover3, l_special1, l_shootAgain, l_aux19, l_aux20, l_10000Rollunder, l_captureLeftTop, l_tripleScoring, l_collectRight, l_aux15, l_aux8, l_lastChanceLeft, l_shooterRod, l_startButton
#                ledB: l_popRight, l_topRollover2, l_special2, l_2xMult, l_3xMult, l_4xMult, l_15000Rollunder, l_collectLeftTop, l_teamPlay1, l_teamPlay2, l_captureRight, l_aux14, l_collectLeftSide, l_aux4
#                ledC: l_popLower, l_topRollover1, l_special3, l_5xMult, l_extraBall, l_aux6, l_regulationPlay1, l_regulationPlay2, l_spinner, l_launchLeftSide, l_aux2, l_specialSpot, l_lastChanceRight
#

#                          GOOD SHOW CODE, need to make new shows
#show_player:
#    mode_attract_started:
 #       pulse_light_show:
 #           speed: 1
 #       blink_light_show:
 #           speed: 1
