#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - start_mode_pops
  mode_base_will_stop:
    - stop_mode_pops

slide_player:
  mode_base_started:
        base_primary_slide:
            target: primary
        base_mini_slide:
            target: mini-display
