#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

# Battle Of The Bands v1.3  MPF 0.80 / GMC 0.1.2 / G'Doh! 4.3

config:
  - config_switches.yaml
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_hardware.yaml
  - config_neoseg_displays.yaml
  - config_keyboard.yaml
  - config_events.yaml
  - config_lights.yaml
#  - config_lights_test.yaml
  - config_targets.yaml
  - config_shots.yaml
  - config_shows.yaml

modes:
  - attract
  - base
  - tilt
  - service

# cc from V1.2
settings:
         replay_score:
            label: Replay Score
            values:
                500000: "500000 (default)"
                1000000: "1000000"
                1500000: "1500000"
            default: 500000
            key_type: int
            sort: 100

#CC from V1.2
machine:
    balls_installed: 8

#CC from V1.2
game:
    balls_per_game: 3
    max_players: 4



#CC from V1.2
playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger
        enable_ball_search: True
        ball_search_timeout: 15s
        ball_search_wait_after_iteration: 10s
        ball_search_interval: 250ms
        ball_search_block_events: flipper_cradle, mode_attract_started, balldevice_bd_trough_ball_eject_success, service_mode_entered
        ball_search_unblock_events: flipper_cradle_release, mode_skillshot_stopped, playfield_active
        ball_search_phase_1_searches: 3
        ball_search_phase_2_searches: 2
        ball_search_phase_3_searches: 3

# CC from V1.2
timed_switches:
    game_cancel:
        switch_tags: start
        time: 5s
        events_when_active: end_game

virtual_platform_start_active_switches:
#  - s_trough1
#  - s_trough2
  - s_m8_trough1
  - s_m16_trough2
  - s_m24_trough3
  - s_m32_trough4
  - s_m40_trough5
  - s_m48_trough6
  - s_m56_trough7
  - s_trough8_opto

# CC from V1.2
flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper_lower
        eos_switch: s_left_flipper_lower_EOS
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: ball_started, flipper_on
        disable_events: ball_will_end, flipper_off
    left_flipper_upper:
        main_coil: c_flipper_left_upper_main
        hold_coil: c_flipper_left_upper_hold
        activation_switch: s_left_flipper_upper
        eos_switch: s_left_flipper_upper_EOS
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: ball_started, flipper_on
        disable_events: ball_will_end, flipper_off
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper_lower
        eos_switch: s_right_flipper_lower_EOS
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: ball_started, flipper_on
        disable_events: ball_will_end, flipper_off
    right_flipper_upper:
        main_coil: c_flipper_right_upper_main
        hold_coil: c_flipper_right_upper_hold
        activation_switch: s_right_flipper_upper
        eos_switch: s_right_flipper_upper_EOS
        use_eos: true
        repulse_on_eos_open: true
        eos_active_ms_before_repulse: 500
        enable_events: ball_started, flipper_on
        disable_events: ball_will_end, flipper_off



named_colors:
   tt_white:   [255,250,240]
   tt_nwhite:  [255,240,200]
   tt_wwhite:  [255,230,170]
   tt_yellow:  [255,220,  0]
   tt_orange:  [255,110,  0]
   tt_blue:    [ 15, 72,255]
   tt_ltblue:  [ 30,144,255]
   tt_red:     [255,  0,  0]
   tt_green:   [  0,255,  0]
   tt_magenta: [255,  0,255]



#CC from V1.2
light_player:
  shutdown:
#    inserts:
#     color: 000002
  #    priority: 1000000
        gi:
            color: off
            priority: 1000000
        group1:
            color: off
            priority: 1000000
  alllightson:
        group1:
            color: green
            priority: 1000000
        gi:
            color: white
            priority: 1000000
  alllightson2:
        group1:
            color: red
            priority: 1000000
        gi:
            color: blue
            priority: 1000000

#    l_pops:
 #     color: off
  #    priority: 1000000
#    l_shooterRod:
 #     color: off
  #    priority: 1000000
#    l_startButton:
 #     color: off
  #    priority: 1000000
#    l_coin:
 #     color: off
  #    priority: 1000000

#CC from V1.2
segment_display_player:
  shutdown:
        neoSegTop:
            text: ""
            priority: 1000000
        neoSegBot:
            text: ""
            priority: 1000000
#        neoSeg_ball:
#            text: ""
#            priority: 1000000
#        neoSeg_2digitxtra:
#            ext: ""
#            priority: 1000000

random_event_player:
  random_lights:
    scope: machine
    events:
      - alllightson
      - alllightson2
