#config_version=6

# Battle Of The Bands v1.3  MPF 0.80 / GMC 0.1.2 / G'Doh! 4.3

# CC from V1.2
#create light group for each NeoSeg display
neoseg_displays:
  neoSeg_0:
    start_channel: "0-0-0"
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_blue

  neoSeg_1:
    start_channel: "0-0-120"
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_blue

  neoSeg_2:
    start_channel: "0-0-240"
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_blue

  neoSeg_3:
    start_channel: "0-0-360"
    size: 8digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_blue

  neoSeg_4:
    start_channel: "0-0-480"
    size: 2digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_blue

  neoSeg_5:
    start_channel: "0-0-510"
    size: 2digit
    light_template:
      type: w
      subtype: led
      color_correction_profile: NeoSeg_blue

#use light groups to arrange into a segment display

segment_displays:
  neoSegTop:
    number: 1
    size: 16
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_0
        - neoSeg_1
      type: 14segment

  neoSegBot:
    number: 1
    size: 16
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_2
        - neoSeg_3
      type: 14segment

  neoSegP1:
    number: 1
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
         - neoSeg_0
      type: 14segment
  neoSegP2:
    number: 1
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
         - neoSeg_1
      type: 14segment
  neoSegP3:
    number: 1
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
         - neoSeg_2
      type: 14segment
  neoSegP4:
    number: 1
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
         - neoSeg_3
      type: 14segment

  neoSegBall:
    number: 1
    size: 4
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_4
      type: 14segment

  neoSeg2nd2d:
    number: 1
    size: 4
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSeg_5
      type: 14segment

#use color_correction_profile whitepoint to adjust the brightness of each
#NeoSeg display
light_settings:
  color_correction_profiles:
    corr_profile_gi:
      whitepoint: [ 1, 1, 1 ]
      gamma: 2.5
    NeoSeg_blue:
      whitepoint: [.5, .5, .5]
