#config_version=6

# Battle Of The Bands v1.3  MPF 0.80 / GMC 0.1.2 / G'Doh! 4.3

# INSERTS are GRB
# GI are RGB
# pop rings grbw

#use color_correction_profile whitepoint to adjust the brightness of each
#NeoSeg display
#light_settings:
#  color_correction_profiles:
#    corr_profile_gi:
#      whitepoint: [ 1, 1, 1 ]
#      gamma: 2.5



#light_stripes:
# popRing:
#   start_channel: 1-0-311    #0-0-480
#   number_template: 1-0-{}
#   light_template:
#     tags: l_pop
#     type: grbw
#     subtype: led
#     color_correction_profile: corr_pop
#   count: 8
# starRing:
#   start_channel: 1-0-343    #0-0-512
#   number_template: 1-0-{}
#   light_template:
#     tags: l_star
#     type: grb
#     subtype: led
#     color_correction_profile: corr_star
#   count: 8

#light_settings:
# color_correction_profiles:
#   corr_star:
#     whitepoint: [0.9, 1, 0.85]
#   corr_pop:
#     whitepoint: [0.85, 0.85, 0.85]
